"""empty message

Revision ID: 0c16a0016dc4
Revises: b8975b3a1a89
Create Date: 2024-01-27 12:39:46.338133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c16a0016dc4'
down_revision = 'b8975b3a1a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_users',
    sa.Column('new_user_id', sa.Integer(), nullable=False),
    sa.Column('new_user_name', sa.String(length=64), nullable=True),
    sa.Column('new_user_tg_id', sa.Integer(), nullable=True),
    sa.Column('new_user_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('new_user_id')
    )
    with op.batch_alter_table('new_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_new_users_new_user_name'), ['new_user_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_users_new_user_tg_id'), ['new_user_tg_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_new_users_new_user_tg_id'))
        batch_op.drop_index(batch_op.f('ix_new_users_new_user_name'))

    op.drop_table('new_users')
    # ### end Alembic commands ###
