"""empty message

Revision ID: 2c412be42ef6
Revises: 31fc24e42dc5
Create Date: 2024-01-13 10:12:04.006029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c412be42ef6'
down_revision = '31fc24e42dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    op.drop_table('classes_1')
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.alter_column('tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.alter_column('tg_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('classes_1',
    sa.Column('class', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numguns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bore', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('displacement', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('classes',
    sa.Column('class', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numguns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bore', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('displacement', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
