"""empty message

Revision ID: 41f06c14f195
Revises: 72d3b38639b3
Create Date: 2024-02-04 16:07:24.195194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f06c14f195'
down_revision = '72d3b38639b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_users',
    sa.Column('new_user_id', sa.Integer(), nullable=False),
    sa.Column('new_user_name', sa.String(length=64), nullable=True),
    sa.Column('new_user_tg_id', sa.Integer(), nullable=True),
    sa.Column('new_user_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('new_user_id')
    )
    with op.batch_alter_table('new_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_new_users_new_user_name'), ['new_user_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_users_new_user_tg_id'), ['new_user_tg_id'], unique=True)

    op.create_table('pupils',
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('pupil_name', sa.String(length=64), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('last_generated_code', sa.String(length=64), nullable=True),
    sa.Column('last_generated_code_date', sa.DateTime(), nullable=True),
    sa.Column('at_school', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pupil_id')
    )
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pupils_last_generated_code'), ['last_generated_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_pupils_pupil_name'), ['pupil_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pupils_tg_id'), ['tg_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_tg_id'), ['tg_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_tg_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pupils_tg_id'))
        batch_op.drop_index(batch_op.f('ix_pupils_pupil_name'))
        batch_op.drop_index(batch_op.f('ix_pupils_last_generated_code'))

    op.drop_table('pupils')
    with op.batch_alter_table('new_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_new_users_new_user_tg_id'))
        batch_op.drop_index(batch_op.f('ix_new_users_new_user_name'))

    op.drop_table('new_users')
    # ### end Alembic commands ###
