"""empty message

Revision ID: b8975b3a1a89
Revises: 57f1e09ef3fa
Create Date: 2024-01-14 17:53:27.488820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8975b3a1a89'
down_revision = '57f1e09ef3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pupils',
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('pupil_name', sa.String(length=64), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('last_generated_code', sa.String(length=64), nullable=True),
    sa.Column('last_generated_code_date', sa.DateTime(), nullable=True),
    sa.Column('at_school', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pupil_id')
    )
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pupils_last_generated_code'), ['last_generated_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pupils_pupil_name'), ['pupil_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pupils_tg_id'), ['tg_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_tg_id'), ['tg_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=2048), nullable=True),
    sa.Column('pupil_id', sa.Integer(), nullable=True),
    sa.Column('code_datetime', sa.DateTime(), nullable=True),
    sa.Column('code_expire_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.pupil_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codes_code_hash'), ['code_hash'], unique=True)

    op.create_table('visits',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=True),
    sa.Column('visit_datetime', sa.DateTime(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.pupil_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codes_code_hash'))

    op.drop_table('codes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_tg_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pupils_tg_id'))
        batch_op.drop_index(batch_op.f('ix_pupils_pupil_name'))
        batch_op.drop_index(batch_op.f('ix_pupils_last_generated_code'))

    op.drop_table('pupils')
    # ### end Alembic commands ###
