"""empty message

Revision ID: c34beb01ec58
Revises: 85dbcb934ebd
Create Date: 2024-01-04 09:54:57.402971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34beb01ec58'
down_revision = '85dbcb934ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=2048), nullable=True),
    sa.Column('pupil_id', sa.Integer(), nullable=True),
    sa.Column('code_datetime', sa.DateTime(), nullable=True),
    sa.Column('code_expire_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.pupil_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codes_code_hash'), ['code_hash'], unique=True)

    op.create_table('visits',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=True),
    sa.Column('visit_datetime', sa.DateTime(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.pupil_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codes_code_hash'))

    op.drop_table('codes')
    # ### end Alembic commands ###
