"""empty message

Revision ID: d175e7b9b516
Revises: c34beb01ec58
Create Date: 2024-01-04 16:28:51.685209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd175e7b9b516'
down_revision = 'c34beb01ec58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index('ix_pupils_pupil_name')
        batch_op.create_index(batch_op.f('ix_pupils_pupil_name'), ['pupil_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pupils_pupil_name'))
        batch_op.create_index('ix_pupils_pupil_name', ['pupil_name'], unique=False)

    # ### end Alembic commands ###
