"""empty message

Revision ID: 7a2e20811868
Revises: 
Create Date: 2023-12-17 12:28:59.796228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2e20811868'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pupils',
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('pupil_name', sa.String(length=64), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('last_generated_code', sa.String(length=64), nullable=True),
    sa.Column('last_generated_code_date', sa.DateTime(), nullable=True),
    sa.Column('at_school', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pupil_id')
    )
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pupils_last_generated_code'), ['last_generated_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pupils_pupil_name'), ['pupil_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_pupils_tg_id'), ['tg_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_tg_id'), ['tg_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_tg_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pupils_tg_id'))
        batch_op.drop_index(batch_op.f('ix_pupils_pupil_name'))
        batch_op.drop_index(batch_op.f('ix_pupils_last_generated_code'))

    op.drop_table('pupils')
    # ### end Alembic commands ###
